language: node_js

node_js:
  - 10.15.0

# only build master and all branches beginning with "beta"
branches:
  only:
    - master
    - test

build:
  ci:
    - pip install sphinx
    - yarn install
    - find ./node_modules/ -exec touch {} +
    - ./node_modules/mocha/bin/mocha "./api/**/!(server).ts"  --reporter mocha-junit-reporter -r ts-node/register --reporter-options mochaFile=shippable/testresults/testresults.xml
    - cat ./shippable/testresults/testresults.xml
    - yarn run build
